name: build-all
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v21
        with:
         nix_conf: experimental-features = nix-command flakes
      - name: Write secrets 4 droid
        env:
          KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
          KEY_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$KEY_PROPERTIES" > android/key.properties
          echo "$KEY_BASE64" | base64 -d > keystore.jks
      - run: nix develop -c flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk/*.apk
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v21
        with:
         nix_conf: experimental-features = nix-command flakes

      - run: nix build -v
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: result/app/*
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v21
        with:
         nix_conf: experimental-features = nix-command flakes
      - run: nix develop -c flutter pub get
      - run: nix develop -c flutter pub run build_runner build -d
      - run: nix develop -c deps2nix
      - uses: EndBug/add-and-commit@v9.1.0
  create-release:
    needs: [build-android, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - run: ls -R
      - run: zip -r -q lin.zip linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: nightly
          body: |
            this is an automatic nightly release
          files: |
            android/*.apk
            lin.zip
