name: build-all
on:
 push:
  paths-ignore:
   - 'README.md'
   
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk/*.apk
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "nix-build"
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: result/app/*