name: build-all
on:
  push:
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NIX_IGNORE_SYSTEMD: 1  # 确保所有作业继承此变量
    steps:
      - uses: actions/checkout@v3
      - name: 前置安装系统依赖  # 新增关键步骤
        run: |
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev curl xz-utils
      - uses: nixbuild/nix-quick-install-action@v21
        with:
          extra_nix_config: |  # 统一参数名
            build-users-group =
            sandbox = false
            experimental-features = nix-command flakes
      - name: Write secrets 4 droid
        env:
          KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
          KEY_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$KEY_PROPERTIES" > android/key.properties
          echo "$KEY_BASE64" | base64 -d > keystore.jks
      - run: nix develop -c flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/app/outputs/flutter-apk/*.apk
  build-linux:
    runs-on: ubuntu-latest
    env:
      NIX_IGNORE_SYSTEMD: 1  # 必须同步配置
    steps:
      - uses: actions/checkout@v3
      - name: 安装系统依赖
        run: sudo apt-get install -y libseccomp-dev
      - uses: nixbuild/nix-quick-install-action@v21
        with:  # 修复参数名
          extra_nix_config: |
            build-users-group =
            sandbox = false
            experimental-features = nix-command flakes
      - run: nix build -v
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: result/app/*
  codegen:
    runs-on: ubuntu-latest
    env:
      NIX_IGNORE_SYSTEMD: 1
    steps:
      - uses: actions/checkout@v3
      - name: 安装系统依赖
        run: sudo apt-get install -y libseccomp-dev
      - uses: nixbuild/nix-quick-install-action@v21
        with:  # 参数名修正
          extra_nix_config: |
            build-users-group =
            sandbox = false
            experimental-features = nix-command flakes
      - run: nix develop -c flutter pub get
      - run: nix develop -c flutter pub run build_runner build -d
      - run: nix develop -c deps2nix
      - uses: EndBug/add-and-commit@v9.1.0
  create-release:
    needs: [build-android, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - run: ls -R
      - run: zip -r -q lin.zip linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: nightly
          body: |
            this is an automatic nightly release
          files: |
            android/*.apk
            lin.zip
